# Generated by Django 4.0.2 on 2022-02-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudenID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Roll', models.CharField(max_length=6)),
                ('RegNo', models.CharField(max_length=6)),
                ('ContactNo', models.CharField(max_length=11)),
                ('ContactAddress', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'STUDENT',
            },
        ),
    ]
