# Generated by Django 4.0.2 on 2022-02-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='StudenID',
            new_name='StudentID',
        ),
    ]
